server {
    listen 80;
    server_name synartech.my www.synartech.my;

    return 301 https://www.synartech.my$request_uri;
}

server {
    listen 443 ssl;
    server_name synartech.my www.synartech.my;

    ssl_certificate /etc/nginx/ssl/synartech.crt;
    ssl_certificate_key /etc/nginx/ssl/synartech.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
